# Use a base image with OpenJDK installed
FROM openjdk:11-jre-slim AS build

# Set the working directory in the container
WORKDIR /app

# Copy the packaged JAR file into the container
COPY target/blog.jar /app/blog.jar

# Expose the port your application runs on
EXPOSE 8080

# Command to run the Spring Boot application
CMD ["java", "-jar", "blog.jar"]

docker build -t blog-image .

docker run -p 8080:8080 blog-image

